# Generated by Django 4.0.4 on 2022-06-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesigQuarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presidente', models.CharField(max_length=30)),
                ('oracao_inicial', models.CharField(max_length=30)),
                ('tesouros', models.CharField(max_length=30)),
                ('joias', models.CharField(max_length=30)),
                ('leitura_tesouros', models.CharField(max_length=30)),
                ('primeira_desig', models.CharField(max_length=30)),
                ('primeira_ajuda', models.CharField(max_length=30)),
                ('segunda_desig', models.CharField(max_length=30)),
                ('segunda_ajuda', models.CharField(max_length=30)),
                ('terceira_desig', models.CharField(max_length=30)),
                ('terceira_ajuda', models.CharField(max_length=30)),
                ('quarta_desig', models.CharField(max_length=30)),
                ('quarta_ajuda', models.CharField(max_length=30)),
                ('nossa_primeira', models.CharField(max_length=30)),
                ('nossa_segunda', models.CharField(max_length=30)),
                ('dirigente_estudo', models.CharField(max_length=30)),
                ('leitor_estudo', models.CharField(max_length=30)),
                ('oracao_final', models.CharField(max_length=30)),
                ('indicador_principal', models.CharField(max_length=30)),
                ('indicador_recepcao', models.CharField(max_length=30)),
                ('volante_um', models.CharField(max_length=30)),
                ('volante_dois', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DesigSabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presidente', models.CharField(max_length=30)),
                ('orador', models.CharField(max_length=30)),
                ('congregacao', models.CharField(max_length=30)),
                ('tema', models.CharField(max_length=30)),
                ('leitor_sentinela', models.CharField(max_length=30)),
                ('indicador_principal', models.CharField(max_length=30)),
                ('indicador_recepcao', models.CharField(max_length=30)),
                ('volante_um', models.CharField(max_length=30)),
                ('volante_dois', models.CharField(max_length=30)),
            ],
        ),
    ]
