# Generated by Django 4.0.4 on 2022-06-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desigquarta',
            old_name='dirigente_estudo',
            new_name='ajudante_01',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='indicador_principal',
            new_name='ajudante_02',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='indicador_recepcao',
            new_name='ajudante_03',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='joias',
            new_name='ajudante_04',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='leitor_estudo',
            new_name='designação_01',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='leitura_tesouros',
            new_name='designação_02',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='nossa_primeira',
            new_name='designação_03',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='nossa_segunda',
            new_name='designação_04',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='oracao_final',
            new_name='dirigente_Estudo',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='oracao_inicial',
            new_name='indicador_Principal',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='primeira_ajuda',
            new_name='indicador_Recepcao',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='primeira_desig',
            new_name='joias_Espirituais',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='quarta_ajuda',
            new_name='leitor_Estudo',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='quarta_desig',
            new_name='leitura_da_Bíblia',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='segunda_ajuda',
            new_name='nossa_Vida_01',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='segunda_desig',
            new_name='nossa_Vida_02',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='terceira_ajuda',
            new_name='oracão_inicial',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='terceira_desig',
            new_name='oração_Final',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='volante_dois',
            new_name='volante_01',
        ),
        migrations.RenameField(
            model_name='desigquarta',
            old_name='volante_um',
            new_name='volante_02',
        ),
    ]
