# Generated by Django 4.0.4 on 2022-06-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0002_rename_dirigente_estudo_desigquarta_ajudante_01_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desigsabado',
            old_name='congregacao',
            new_name='congregação',
        ),
        migrations.RenameField(
            model_name='desigsabado',
            old_name='indicador_principal',
            new_name='indicador_Principal',
        ),
        migrations.RenameField(
            model_name='desigsabado',
            old_name='indicador_recepcao',
            new_name='indicador_Recepcao',
        ),
        migrations.RenameField(
            model_name='desigsabado',
            old_name='leitor_sentinela',
            new_name='leitor_da_Sentinela',
        ),
        migrations.RenameField(
            model_name='desigsabado',
            old_name='volante_dois',
            new_name='volante_01',
        ),
        migrations.RenameField(
            model_name='desigsabado',
            old_name='volante_um',
            new_name='volante_02',
        ),
        migrations.RemoveField(
            model_name='desigquarta',
            name='oracão_inicial',
        ),
    ]
