# Generated by Django 4.0.4 on 2022-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0003_rename_congregacao_desigsabado_congregação_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desigquarta',
            name='oração_Inicial',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
