# Generated by Django 4.0.4 on 2022-06-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0004_desigquarta_oração_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desigquarta',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
