# Generated by Django 4.0.4 on 2022-06-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0005_alter_desigquarta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desigquarta',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='oração_Inicial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='presidente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='tesouros',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
