# Generated by Django 4.0.4 on 2022-06-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0006_alter_desigquarta_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desigquarta',
            name='ajudante_01',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='ajudante_02',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='ajudante_03',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='ajudante_04',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='designação_01',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='designação_02',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='designação_03',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='designação_04',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='dirigente_Estudo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='indicador_Principal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='indicador_Recepcao',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='joias_Espirituais',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='leitor_Estudo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='leitura_da_Bíblia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='nossa_Vida_01',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='nossa_Vida_02',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='oração_Final',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='volante_01',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='volante_02',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
