# Generated by Django 4.0.4 on 2022-06-09 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0008_alter_desigsabado_congregação_alter_desigsabado_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desigquarta',
            old_name='indicador_Recepcao',
            new_name='indicador_Recepção',
        ),
        migrations.RenameField(
            model_name='desigsabado',
            old_name='indicador_Recepcao',
            new_name='indicador_Recepção',
        ),
    ]
