# Generated by Django 4.0.5 on 2022-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0012_alter_desigquarta_dirigente_estudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desigquarta',
            name='indicador_Principal',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('David', 'David'), ('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Pierre', 'Pierre'), ('Vanoel', 'Vanoel'), ('Paulo Moura', 'Paulo Moura'), ('Paulo Copque', 'Paulo Copque'), ('Samuel', 'Samuel'), ('Ronaldo', 'Ronaldo'), ('Gilson', 'Gilson'), ('Jardas', 'Jardas'), ('Wesley', 'Wesley'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='indicador_Recepção',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('David', 'David'), ('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Pierre', 'Pierre'), ('Vanoel', 'Vanoel'), ('Paulo Moura', 'Paulo Moura'), ('Paulo Copque', 'Paulo Copque'), ('Samuel', 'Samuel'), ('Ronaldo', 'Ronaldo'), ('Gilson', 'Gilson'), ('Jardas', 'Jardas'), ('Wesley', 'Wesley'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='oração_Final',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('Joselito', 'Joselito'), ('Vanoel', 'Vanoel'), ('Paulo Copque', 'Paulo Copque'), ('Paulo Moura', 'Paulo Moura'), ('Pierre', 'Pierre')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='volante_01',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('David', 'David'), ('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Pierre', 'Pierre'), ('Vanoel', 'Vanoel'), ('Paulo Moura', 'Paulo Moura'), ('Paulo Copque', 'Paulo Copque'), ('Samuel', 'Samuel'), ('Ronaldo', 'Ronaldo'), ('Gilson', 'Gilson'), ('Jardas', 'Jardas'), ('Wesley', 'Wesley'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='volante_02',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('David', 'David'), ('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Pierre', 'Pierre'), ('Vanoel', 'Vanoel'), ('Paulo Moura', 'Paulo Moura'), ('Paulo Copque', 'Paulo Copque'), ('Samuel', 'Samuel'), ('Ronaldo', 'Ronaldo'), ('Gilson', 'Gilson'), ('Jardas', 'Jardas'), ('Wesley', 'Wesley'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigsabado',
            name='indicador_Principal',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('David', 'David'), ('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Pierre', 'Pierre'), ('Vanoel', 'Vanoel'), ('Paulo Moura', 'Paulo Moura'), ('Paulo Copque', 'Paulo Copque'), ('Samuel', 'Samuel'), ('Ronaldo', 'Ronaldo'), ('Gilson', 'Gilson'), ('Jardas', 'Jardas'), ('Wesley', 'Wesley'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigsabado',
            name='indicador_Recepção',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('David', 'David'), ('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Pierre', 'Pierre'), ('Vanoel', 'Vanoel'), ('Paulo Moura', 'Paulo Moura'), ('Paulo Copque', 'Paulo Copque'), ('Samuel', 'Samuel'), ('Ronaldo', 'Ronaldo'), ('Gilson', 'Gilson'), ('Jardas', 'Jardas'), ('Wesley', 'Wesley'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigsabado',
            name='volante_01',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('David', 'David'), ('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Pierre', 'Pierre'), ('Vanoel', 'Vanoel'), ('Paulo Moura', 'Paulo Moura'), ('Paulo Copque', 'Paulo Copque'), ('Samuel', 'Samuel'), ('Ronaldo', 'Ronaldo'), ('Gilson', 'Gilson'), ('Jardas', 'Jardas'), ('Wesley', 'Wesley'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigsabado',
            name='volante_02',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('David', 'David'), ('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Pierre', 'Pierre'), ('Vanoel', 'Vanoel'), ('Paulo Moura', 'Paulo Moura'), ('Paulo Copque', 'Paulo Copque'), ('Samuel', 'Samuel'), ('Ronaldo', 'Ronaldo'), ('Gilson', 'Gilson'), ('Jardas', 'Jardas'), ('Wesley', 'Wesley'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
    ]
