# Generated by Django 4.0.4 on 2022-08-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0014_alter_desigquarta_indicador_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desigquarta',
            name='indicador_Principal',
            field=models.CharField(blank=True, choices=[('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Vanoel', 'Vanoel'), ('Ronaldo', 'Ronaldo'), ('Isac', 'Isac'), ('Arnaldo', 'Arnaldo'), ('José', 'José'), ('Paulo Copque', 'Paulo Copque'), ('Gilson', 'Gilson'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('David', 'David'), ('Pierre', 'Pierre'), ('Samuel', 'Samuel'), ('Jardas', 'Jardas'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='indicador_Recepção',
            field=models.CharField(blank=True, choices=[('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Vanoel', 'Vanoel'), ('Ronaldo', 'Ronaldo'), ('Isac', 'Isac'), ('Arnaldo', 'Arnaldo'), ('José', 'José'), ('Paulo Copque', 'Paulo Copque'), ('Gilson', 'Gilson'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('David', 'David'), ('Pierre', 'Pierre'), ('Samuel', 'Samuel'), ('Jardas', 'Jardas'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='oração_Final',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Vanoel', 'Vanoel'), ('Joselito', 'Joselito'), ('Arnaldo', 'Arnaldo'), ('Isac', 'Isac'), ('Samuel', 'Samuel'), ('Paulo Copque', 'Paulo Copque'), ('Pierre', 'Pierre'), ('Paulo Moura', 'Paulo Moura')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='volante_01',
            field=models.CharField(blank=True, choices=[('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Vanoel', 'Vanoel'), ('Ronaldo', 'Ronaldo'), ('Isac', 'Isac'), ('Arnaldo', 'Arnaldo'), ('José', 'José'), ('Paulo Copque', 'Paulo Copque'), ('Gilson', 'Gilson'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('David', 'David'), ('Pierre', 'Pierre'), ('Samuel', 'Samuel'), ('Jardas', 'Jardas'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='volante_02',
            field=models.CharField(blank=True, choices=[('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Vanoel', 'Vanoel'), ('Ronaldo', 'Ronaldo'), ('Isac', 'Isac'), ('Arnaldo', 'Arnaldo'), ('José', 'José'), ('Paulo Copque', 'Paulo Copque'), ('Gilson', 'Gilson'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('David', 'David'), ('Pierre', 'Pierre'), ('Samuel', 'Samuel'), ('Jardas', 'Jardas'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigsabado',
            name='indicador_Principal',
            field=models.CharField(blank=True, choices=[('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Vanoel', 'Vanoel'), ('Ronaldo', 'Ronaldo'), ('Isac', 'Isac'), ('Arnaldo', 'Arnaldo'), ('José', 'José'), ('Paulo Copque', 'Paulo Copque'), ('Gilson', 'Gilson'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('David', 'David'), ('Pierre', 'Pierre'), ('Samuel', 'Samuel'), ('Jardas', 'Jardas'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigsabado',
            name='indicador_Recepção',
            field=models.CharField(blank=True, choices=[('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Vanoel', 'Vanoel'), ('Ronaldo', 'Ronaldo'), ('Isac', 'Isac'), ('Arnaldo', 'Arnaldo'), ('José', 'José'), ('Paulo Copque', 'Paulo Copque'), ('Gilson', 'Gilson'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('David', 'David'), ('Pierre', 'Pierre'), ('Samuel', 'Samuel'), ('Jardas', 'Jardas'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigsabado',
            name='volante_01',
            field=models.CharField(blank=True, choices=[('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Vanoel', 'Vanoel'), ('Ronaldo', 'Ronaldo'), ('Isac', 'Isac'), ('Arnaldo', 'Arnaldo'), ('José', 'José'), ('Paulo Copque', 'Paulo Copque'), ('Gilson', 'Gilson'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('David', 'David'), ('Pierre', 'Pierre'), ('Samuel', 'Samuel'), ('Jardas', 'Jardas'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigsabado',
            name='volante_02',
            field=models.CharField(blank=True, choices=[('Isaías', 'Isaías'), ('Joselito', 'Joselito'), ('Vanoel', 'Vanoel'), ('Ronaldo', 'Ronaldo'), ('Isac', 'Isac'), ('Arnaldo', 'Arnaldo'), ('José', 'José'), ('Paulo Copque', 'Paulo Copque'), ('Gilson', 'Gilson'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('David', 'David'), ('Pierre', 'Pierre'), ('Samuel', 'Samuel'), ('Jardas', 'Jardas'), ('Ueliton', 'Ueliton')], max_length=30, null=True),
        ),
    ]
