# Generated by Django 4.0.5 on 2022-08-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0015_alter_desigquarta_indicador_principal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desigquarta',
            options={'ordering': ['data']},
        ),
        migrations.AlterModelOptions(
            name='desigsabado',
            options={'ordering': ['data']},
        ),
        migrations.AlterField(
            model_name='desigsabado',
            name='tema',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
