# Generated by Django 4.0.5 on 2022-08-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0016_alter_desigquarta_options_alter_desigsabado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desigsabado',
            name='tema',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
