# Generated by Django 4.0.5 on 2022-12-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designacoes', '0019_alter_desigquarta_indicador_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desigquarta',
            name='dirigente_Estudo',
            field=models.CharField(blank=True, choices=[('Jeferson', 'Jeferson'), ('Elidomar', 'Elidomar'), ('Abel', 'Abel'), ('Geraldo', 'Geraldo'), ('Isac', 'Isac')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='joias_Espirituais',
            field=models.CharField(blank=True, choices=[('Jeferson', 'Jeferson'), ('Elidomar', 'Elidomar'), ('Abel', 'Abel'), ('Geraldo', 'Geraldo'), ('José', 'José'), ('Douglas', 'Douglas'), ('Nelito', 'Nelito'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('Paulo Copque', 'Paulo Copque'), ('Joselito', 'Joselito'), ('Romenil', 'Romenil'), ('Pierre', 'Pierre')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='nossa_Vida_01',
            field=models.CharField(blank=True, choices=[('Jeferson', 'Jeferson'), ('Elidomar', 'Elidomar'), ('Abel', 'Abel'), ('Geraldo', 'Geraldo'), ('José', 'José'), ('Douglas', 'Douglas'), ('Nelito', 'Nelito'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('Paulo Copque', 'Paulo Copque'), ('Joselito', 'Joselito'), ('Romenil', 'Romenil'), ('Pierre', 'Pierre')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='nossa_Vida_02',
            field=models.CharField(blank=True, choices=[('Jeferson', 'Jeferson'), ('Elidomar', 'Elidomar'), ('Abel', 'Abel'), ('Geraldo', 'Geraldo'), ('José', 'José'), ('Douglas', 'Douglas'), ('Nelito', 'Nelito'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('Paulo Copque', 'Paulo Copque'), ('Joselito', 'Joselito'), ('Romenil', 'Romenil'), ('Pierre', 'Pierre')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='oração_Final',
            field=models.CharField(blank=True, choices=[('José', 'José'), ('Douglas', 'Douglas'), ('Vanoel', 'Vanoel'), ('Joselito', 'Joselito'), ('Arnaldo', 'Arnaldo'), ('Isac', 'Isac'), ('Samuel', 'Samuel'), ('Paulo Copque', 'Paulo Copque'), ('Pierre', 'Pierre'), ('Paulo Moura', 'Paulo Moura'), ('Romenil', 'Romenil')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='oração_Inicial',
            field=models.CharField(blank=True, choices=[('Jeferson', 'Jeferson'), ('Elidomar', 'Elidomar'), ('Abel', 'Abel'), ('Geraldo', 'Geraldo'), ('Isac', 'Isac')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='presidente',
            field=models.CharField(blank=True, choices=[('Jeferson', 'Jeferson'), ('Elidomar', 'Elidomar'), ('Abel', 'Abel'), ('Geraldo', 'Geraldo'), ('Isac', 'Isac')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigquarta',
            name='tesouros',
            field=models.CharField(blank=True, choices=[('Jeferson', 'Jeferson'), ('Elidomar', 'Elidomar'), ('Abel', 'Abel'), ('Geraldo', 'Geraldo'), ('José', 'José'), ('Douglas', 'Douglas'), ('Nelito', 'Nelito'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('Paulo Copque', 'Paulo Copque'), ('Joselito', 'Joselito'), ('Romenil', 'Romenil'), ('Pierre', 'Pierre')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='desigsabado',
            name='presidente',
            field=models.CharField(blank=True, choices=[('Jeferson', 'Jeferson'), ('Elidomar', 'Elidomar'), ('Abel', 'Abel'), ('Geraldo', 'Geraldo'), ('José', 'José'), ('Douglas', 'Douglas'), ('Nelito', 'Nelito'), ('Isac', 'Isac'), ('Vanoel', 'Vanoel'), ('Samuel', 'Samuel'), ('Arnaldo', 'Arnaldo'), ('Paulo Copque', 'Paulo Copque'), ('Joselito', 'Joselito'), ('Romenil', 'Romenil'), ('Pierre', 'Pierre')], max_length=30, null=True),
        ),
    ]
