# Generated by Django 4.0.5 on 2022-07-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='telefone_emergencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
