# Generated by Django 4.0.5 on 2022-07-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contatos_telefone_emergencia_alter_contatos_telefone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatos',
            old_name='telefone_emergencia',
            new_name='contato_de_Emergência',
        ),
    ]
