# Generated by Django 4.0.4 on 2022-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_rename_telefone_emergencia_contatos_contato_de_emergência'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='contato_de_Emergência',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contatos',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
